// Generated by LiveScript 1.6.0
(function(){
  var clockTick;
  clockTick = function(){
    var currentTime, month, day, year, hours, minutes, text;
    currentTime = new Date();
    month = currentTime.getMonth() + 1;
    day = currentTime.getDate();
    year = currentTime.getFullYear();
    hours = currentTime.getHours();
    minutes = currentTime.getMinutes();
    text = day + "-" + month + "-" + year + ' ' + hours + ':' + minutes;
    return document.querySelector('.date').innerHTML = text;
  };
  setInterval(clockTick, 1000);
}).call(this);
